language: bash
script: true
sudo: required
before_install:
- bash scripts/install.sh
group: stable
dist: precise
os: linux
notifications:
  slack:
    secure: EsQKZ74lxpgOaA40f1sPxchPSv5W21UotednW3Q55t/xy/2ZZbk+eYb2r6oZCV2Ik3iqlv719Ds0CAr3+rwM2G4fCr4NNfVAVBUgm/0QXXjIy/2cpPCKEgB/sXuNzdcWjRl54jw7RQHT5GCyw/k4iyrPPO6TzpG1mu3ZNlsgsBb16PCE6PO353Ex7HuaeLN009+6omPYzyGi3XgBUbfhw5HUZhBkNIGhK/IR67FF9SV7oOesBuudigR0mos3kT+pOPAVtVqnIBHdUxDLz0V75Sfn1DYb5ktblYGocjhD6szBHtf9hT4L7AO07T0tLzcht6DC16FuY+QaXDTapGJmW6S+kVNekv9QIrhzSAYUSHKh3Y7wVgnQ8smd6uvKfCAKp2c90oXUm6p0zIU2A4lARCwenmhKkr5oxHAuiEnOdI1BKVEgImU9bWUle/2v3ww72HGl/JgLxUj3trwYFbjtG2sgabtmv6drjlJnv65IYYORmYve3/+adOedHvVbhVkydY5D+xWoJCh47vgUGhPItkqEtdGMYVtJB7HsdB1+wTcXA4EwpPjcFIQT2g9l3I5pwa8IuPaWYkdV3f3aYdZtv5Gsgba3OJ68Z5BkHS4Sk1Ab2+2lBALqJQ9TtLsrAspPVfSdoq365wbIuKRP+O0+7gw+k+vYZk5tuFpQB5FgDW0=
  on_failure: always
