language: bash
script: true
sudo: required
before_install:
- bash scripts/install.sh
group: stable
dist: precise
os: linux
notifications:
  slack:
    secure: HRS1pcJJF4ezDy16sloINBvDA9zL8TDP6y1Y7JoT+eLsNhaq0HSE9v35H95Pbqkg9oYJIS7JFVBjWLhFSpTZzDEScAtsxxW4TSBQfNluPYv1p34KTt4OoBUluNwwMdKYJyyTw6wdvn8wAf2QkROnTRXhPny/Bgv75iyw90Bu4rOYjUqipw0UwZizy8DZZeJOqd9+BdcmmbwWaqHFPra5MneGbnzCkNiytHSprqwbGjUNvyofE9F5wWzwLwDYIpZlAY9f8+b+dY44ZoY4DcY2wFUjY3P5IrXYNKwCHEUjMh09/MC4YbQghV0l6qHgQI0GvNynZuTzxp65pPW4+IwY3QagtjmYYoP0+NUR+dxr9/xToC4Q02oGQ1SutNqN+lKUgOM+qk5EQFs+/t4tm7yADtNjk6+Gq44C8v8uQbzxvUxkH4iyZ1NaeYzKXdnPEwqh4JZZBGt18V13mJY9SsS8uNQuITWjGObwfMyMFax0TuuJTA6WJhK1+SrJpS9XHVAPMSd+CrjcM29pZjXB2so6wTmjCjh70xXgmecfTFIea4NWxwOaHW9hD1GXyr87pTyfN1Cv89nVhXhG1bxWLOstcUc8ruw/5qgo7TxzsvaXv2CuRmMfbHK7iqZpO9K1/X0+Ai32bUTL9RZBqYlFNqysN2z/c4LOUWdwhw9o1zbKhYU=
