apiVersion: v1
kind: Pod
metadata:
  name: setup
spec:
  restartPolicy: Never
  containers:
  - name: setup
    image: anthonyamanse/mysql-bookinfo
    imagePullPolicy: Always
    env:
    - name: MYSQL_DB_USER
      value: 'PLACEHOLDER_DB_USER'
    - name: MYSQL_DB_PASSWORD
      value: 'PLACEHOLDER_DB_PASSWORD'
    - name: MYSQL_DB_HOST
      value: 'PLACEHOLDER_DB_HOST'
    - name: MYSQL_DB_PORT
      value: 'PLACEHOLDER_DB_PORT'
