apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratings-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - name: ratings
        image: anthonyamanse/ratings-v1
        imagePullPolicy: Always
        env:
        - name: MYSQL_DB_USER
          value: 'PLACEHOLDER_DB_USER'
        - name: MYSQL_DB_PASSWORD
          value: 'PLACEHOLDER_DB_PASSWORD'
        - name: MYSQL_DB_HOST
          value: 'PLACEHOLDER_DB_HOST'
        - name: MYSQL_DB_PORT
          value: 'PLACEHOLDER_DB_PORT'
        ports:
        - containerPort: 9080
